#!/usr/bin/python
import boto3
client = boto3.client('route53')
ec2 = boto3.resource('ec2')
ec2list = []
r = client.list_resource_record_sets(HostedZoneId='ZU3VY3K6ELLX5')

for i in r["ResourceRecordSets"]:
 print(ResourceRecordSets) 
 if i['Type'] == 'A' and 'plbus' in i['Name']:
   #if 'plbus' in i['Name']:
     pair = i['ResourceRecords'][0]     
     ec2list.append(pair['Value'])
     for instance in ec2.instances.all():
      		if instance.private_ip_address in ec2list:
      			print  instance.private_ip_address, i['Name'], pair['Value'], instance.id, instance.instance_type, ec2list.index(instance.private_ip_address)               
            ec2list.remove(instance.private_ip_address)
        		break
      		else:
      			continue     
